context:
  ami: "ami-0c6e5afdd23291f73"

ami: "ami-0c6e5afdd23291f73"

instance_name: "humanizone-bastion"
security_group_name: "humanizone-bastion-sg"
key_name: "humani"

remote_states:
  "network":
    organization: "humanizone"
    workspace: "network"
